Serilog:
  Using: [ "Serilog.Sinks.Console", "Serilog.Sinks.Loki" ]
  MinimumLevel:
    Default: Information
    Override:
      SS14: Debug
      Microsoft: "Warning"
      Microsoft.Hosting.Lifetime: "Information"
      Microsoft.AspNetCore: Warning

  WriteTo:
    - Name: Console
      Args:
        OutputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}"

  #Enrich: [ "FromLogContext" ]

  #Loki:
  #  Address: "http://localhost:3100"
  #  Name: "Test"

# Important if using Git update method
BaseUrl: "http://localhost:5000/"

AllowedHosts: "*"



Servers:
  Instances:
    # ID of your server.
    default:
      Name: "Server"
      # ApiToken: "foobar" # API token to control this instance remotely like run updates, restart server. This should be confidential
      ApiPort: 1212 # API port OF THE GAME SERVER. This has to match the 1212 HTTP status API (described below). Otherwise the watchdog can't contact the game server for stuff.

      UpdateType: "Git"
      Updates:
        BaseUrl: "https://github.com/space-wizards/space-station-14"
          #Branch: "default"
      
      TimeoutSeconds: 120

